# 服务启动的端口
server:
  port: 8082
  
# 网关本身也是一个微服务
spring: 
  application: 
    name: paas-gateway

# 配置注册中心地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    healthcheck: 
      enabled: true #开启健康检查
# 网关设置     
zuul:
  host:
    connect-timeout-mills: 60000